anthropic:
  "claude-sonnet-4-20250514":
    input_token_price: 3.0
    output_token_price: 15.0
    cache_creation_token_price: 3.75
    cache_read_token_price: 0.3
  "claude-3-7-sonnet-20250219":
    input_token_price: 3.0
    output_token_price: 15.0
    cache_creation_token_price: 3.75
    cache_read_token_price: 0.3
openai:
  "gpt-4.1":
    input_token_price:  2.0
    cache_input_token_price: 0.5
    output_token_price: 8.0
openai_response:
  "o3":
    input_token_price:  2.0
    cache_input_token_price: 0.5
    output_token_price: 8.0
  "o4-mini":
    input_token_price:  1.1
    cache_input_token_price: 0.275
    output_token_price: 4.4
qwen:
  "qwen3-32b":
    input_token_price: 0.0
    cache_input_token_price: 0.0
    output_token_price: 0.0
  "qwen3-14b":
    input_token_price: 0.0
    cache_input_token_price: 0.0
    output_token_price: 0.0 
