# conf/llm/default.yaml - Default LLM configuration
provider: "openai" # openai, qwen, anthropic, gemini, deepseek
model_name: "gpt-4.1" # gpt-4.1, qwen3-14b, claude-sonnet-4-20250514, claude-3-7-sonnet-20250219, gemini-1.5-pro, deepseek-chat
async_client: false
temperature: 0.3
top_p: 1.0
min_p: 0.0
top_k: -1
max_tokens: 4096
openai_base_url: null
keep_tool_result: -1
anthropic_base_url: https://api.anthropic.com
